/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";


export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./hennita.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base_metal.geometry}
        material={materials["base de metal"]}
        position={[-1.99, 0.34, -0.1]}
        scale={[0.82, 0.1, 0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tostado.geometry}
        material={materials.prueba_tono}
        position={[-1.99, 0.35, -0.1]}
        scale={[0.79, 0.1, 0.79]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cacao.geometry}
        material={materials["Material.018"]}
        position={[2.04, 0.35, -0.1]}
        scale={[0.79, 0.1, 0.79]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.base.geometry}
        material={materials["Material.004"]}
        position={[0.06, 0.31, -0.08]}
        scale={[3.27, 0.17, 2.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.choco.geometry}
        material={materials["Material.017"]}
        position={[0.01, 0.35, -0.1]}
        scale={[0.79, 0.1, 0.79]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Textura_interior.geometry}
        material={materials["Material.006"]}
        position={[0.06, 2.57, -2.33]}
        scale={[3.37, 1.95, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["base-tapa"].geometry}
        material={materials.Material}
        position={[0.06, 0.12, 0]}
        scale={[3.5, -0.02, 2.21]}
      />
    </group>
  );
}


useGLTF.preload("./hennita.gltf");
